# Generated by Django 4.1.7 on 2023-03-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsitem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='md5',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
