# Generated by Django 4.1.7 on 2023-03-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_fix_fillin_news_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='md5',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
